#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ListViewSample.Droid.Resource", IsApplication=true)]

namespace ListViewSample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int colorAccent = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int colorPrimary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int colorPrimaryDark = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ramen1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ramen2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ramen3 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ramen4 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ramen5 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ramen6 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ramen7 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ramen8 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ramen9 = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int Image = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int MainText = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int RightArrow = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int SubText = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int button1 = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int button2 = 2131165194;
			
			// aapt resource value: 0x7f070003
			public const int customListView = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int customListViewAddButton = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int customListViewDeleteButton = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f07000b
			public const int mainAddButton = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int mainDeleteButton = 2131165196;
			
			// aapt resource value: 0x7f070004
			public const int relativeLayout1 = 2131165188;
			
			// aapt resource value: 0x7f07000d
			public const int simpleListView = 2131165197;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomListView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SimpleListItem1 = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
