#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ListViewSample.Droid.Resource", IsApplication=true)]

namespace ListViewSample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ramen1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ramen2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ramen3 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ramen4 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ramen5 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ramen6 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ramen7 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ramen8 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ramen9 = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int AgeText = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int Image = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int NameText = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int RightArrow = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int button1 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int button2 = 2131034122;
			
			// aapt resource value: 0x7f050003
			public const int customListView = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int customListViewAddButton = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int customListViewDeleteButton = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int mainAddButton = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int mainDeleteButton = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int relativeLayout1 = 2131034116;
			
			// aapt resource value: 0x7f05000d
			public const int simpleListView = 2131034125;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomListView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SimpleListItem1 = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
